<?php
/**
 * User Repository is for basic data update or access to user table.
 * 
 * @author: Ezra Carter
 */
require_once "src/util/sql/BaseSQL.php";
require_once "src/util/sql/Util.php";
require_once "src/user/repo/Repository.php";
require_once "src/util/sql/Interface.php";
require_once "src/user/model/User.php";

class Repository
{
    private static $db;

    function __construct(SqlInterface $db)
    {
        self::$db = $db;
    }

    // get a user
    public function get(string $id): User
    {
        $getUserQuery = "SELECT * FROM User WHERE user_id = ?";
        $ite = self::$db->accessorQuery($getUserQuery, "s", $id);

        $user = new User;
        $ite->scan(...$user->toRefList());
        $ite->next();

        return $user;
    }

    // create a user
    public function create(string $email, string $password, string $userID = null): string
    {
        $usr = new User;

        // Want to use our autogenerated user id's in general
        if ($userID) {
            $usr->user_id = $userID;
        }
        $usr->email = $email;
        $usr->password = password_hash($password);

        $createUserQuery = sprintf("INSERT INTO User VALUES (%s)", Sql::getStatementParams(7));

        if(self::$db->mutatorQuery($createUserQuery, "sssisss", ...$usr->toRefList())) {
            return $usr->user_id;
        }

        return "";
    }

    // update a user
    public function update(User $user): bool
    {
        $updateUserQuery = "UPDATE User SET password = ?, is_admin = ?, email = ?, modified = ? WHERE user_id = ?";

        return self::$db->mutatorQuery($updateUserQuery, "sisss", password_hash($user->password), $user->is_admin, $user->email, getSqlNow(), $user->user_id);
    }

    public function verify(string $email, string $password): string
    {
        $getByEmail = "SELECT * FROM User WHERE email = ?";
        $ite = self::$db->accessorQuery($getUserQuery, "s", $email);

        $user = new User;
        $ite->scan(...$user->toRefList());
        $ite->next();

        if ($user->verifyPassword($password)) {
            return $user->user_id;
        }

        return "";
    }
}

?>
