<?php
/**
 * User Repository is for basic data update or access to user table.
 * 
 * @author: Ezra Carter
 */
require_once "src/util/sql/BaseSQL.php";
require_once "src/user/repo/Repository.php";
require_once "src/util/sql/Interface.php";
require_once "src/user/model/User.php";

class UserRepository
{
    private static $db;

    function __construct(SqlInterface $db)
    {
        self::$db = $db;
    }

    // get a user
    public function get(string $id): User
    {
        $getUserQuery = "SELECT * FROM User WHERE user_id = ?";
        $ite = self::$db->accessorQuery($getUserQuery, "s", $id);

        $user = new User;
        $refs = $user->toRefList();
        $ite->scan(...$refs);
        $ite->next();

        return $user;
    }

    // create a user
    public function create($first_name, $last_name, $email, $user_id = null): bool
    {
        $usr = new User;

        // Want to user our autogenerated user id's in general
        if ($user_id) {
            $usr->user_id = $user_id;
        }
        $usr->first_name = $first_name;
        $usr->last_name = $last_name;
        $usr->email = $email;
        $createUserQuery = sprintf("INSERT INTO User VALUES (%s)", Sql::getStatementParams(7));
        return self::$db->mutatorQuery($createUserQuery, "sssssss", ...$usr->toRefList());
    }
}

?>
