<?php
/**
 * User Repository is for basic data update or access to user table.
 * 
 * @author: Ezra Carter
 */
require_once "src/util/sql/BaseSQL.php";
require_once "src/util/sql/Util.php";
require_once "src/user/repo/Repository.php";
require_once "src/util/sql/Interface.php";
require_once "src/user/model/User.php";

class UserRepository
{
    private static $db;

    function __construct(SqlInterface $db)
    {
        self::$db = $db;
    }

    // get a user
    public function get(string $id): User
    {
        $getUserQuery = "SELECT * FROM User WHERE user_id = ?";
        $ite = self::$db->accessorQuery($getUserQuery, "s", $id);

        $user = new User;
        $ite->scan(...$user->toRefList());
        $ite->next();

        return $user;
    }

    // create a user
    public function create(string $firstName, string $lastName, string $email, string $userID = null): string
    {
        $usr = new User;

        // Want to use our autogenerated user id's in general
        if ($userID) {
            $usr->user_id = $userID;
        }
        $usr->first_name = $firstName;
        $usr->last_name = $lastName;
        $usr->email = $email;

        $createUserQuery = sprintf("INSERT INTO User VALUES (%s)", Sql::getStatementParams(7));

        if(self::$db->mutatorQuery($createUserQuery, "sssssss", ...$usr->toRefList())) {
            return $usr->user_id;
        }

        return "";
    }

    // update a user
    public function update(User $user): bool
    {
        $updateUserQuery = "UPDATE User SET first_name = ?, last_name = ?, email = ?, modified = ? WHERE user_id = ?";

        return self::$db->mutatorQuery($updateUserQuery, "sssss", $user->first_name, $user->last_name, $user->email, getSqlNow(), $user->user_id);
    }
}

?>
